base_model = "google/gemini-3-flash-preview"

[[reasoning_options]]
type = "effort"
values = ["none", "low", "medium", "high", "max"]

[cost]
input = 0.25
output = 1.5
cache_read = 0.025
cache_write = 0.5

[limit]
output = 65_535
